version: '3.3'
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  gate-simulator:
    build: ./gate-simulator
    image: gate-simulator
    ports:
      - '9999:9999'
  aqa-shop:
    build: ./app
    image: aqa-shop
    ports:
      - '8080:8080'
